/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffe16d",
        "on-surface-variant": "#554336",
        "on-tertiary-fixed": "#281719",
        "primary-fixed": "#ffdcc3",
        "surface": "#fff8f4",
        "surface-container-high": "#f0e6e0",
        "outline": "#887364",
        "surface-container-highest": "#eae1db",
        "on-primary": "#ffffff",
        "surface-container": "#f5ece6",
        "background": "#fff8f4",
        "on-secondary-fixed-variant": "#544600",
        "secondary-fixed-dim": "#e9c400",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#debfc2",
        "primary-fixed-dim": "#ffb77d",
        "surface-dim": "#e1d8d3",
        "on-tertiary-fixed-variant": "#574144",
        "on-tertiary-container": "#4a3538",
        "on-primary-fixed-variant": "#6e3900",
        "secondary-container": "#fcd400",
        "on-background": "#1f1b17",
        "tertiary-fixed": "#fbdbde",
        "error": "#ba1a1a",
        "surface-container-low": "#fbf2ec",
        "primary-container": "#f28c28",
        "inverse-on-surface": "#f8efe9",
        "tertiary-container": "#bb9ea1",
        "surface-variant": "#eae1db",
        "on-surface": "#1f1b17",
        "tertiary": "#70585b",
        "inverse-primary": "#ffb77d",
        "surface-bright": "#fff8f4",
        "on-secondary-fixed": "#221b00",
        "surface-tint": "#914d00",
        "on-secondary-container": "#6e5c00",
        "inverse-surface": "#34302c",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#2f1500",
        "on-error-container": "#93000a",
        "outline-variant": "#dbc2b0",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#705d00",
        "on-primary-container": "#5d2f00",
        "primary": "#914d00",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        serif: ["Noto Serif", "serif"],
        sans: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
    }
  },
  plugins: [],
}

